apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: sidecar-injector-configuration
  annotations:
    cert-manager.io/inject-ca-from: default/selfsigned-cert
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUxieEVnNjNpbHFWOElhcUFZQTZTaXN3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa00yUTNaV1JpWXpJdE5UaGlOaTAwTkdWbUxUZ3pNall0WlRCa09HWmhOMlF6TVROaApNQ0FYRFRJek1UQXhOakV6TURVeE4xb1lEekl3TlRNeE1EQTRNVFF3TlRFM1dqQXZNUzB3S3dZRFZRUURFeVF6ClpEZGxaR0pqTWkwMU9HSTJMVFEwWldZdE9ETXlOaTFsTUdRNFptRTNaRE14TTJFd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDNW93cUY0U3lHM2tKelRJdURscXVKb1JPUWtZSG9ia1N2M3cvVQpCMjJBWmJLZWxIWWszMm9waEFvR3B0SG5DbG5wYTI3RWc1SXdXUzJSL0NPRUtNaTNTcXZtbnc3bzlZZ05WNFFvCmU4bTRrRUs3bS9IREkxQUluZ0tlZi83UWt1dmlNbFdjNnp5b1dtYnhVUFBqbVBUY1hmOSsyUHljcXdKVUQ5US8KYzh5RDJPWHc4L1hmbFltNndOVU5aUC82T1NXeTh0Z0NROG9NMVdLc3VEcFpvOTJBYnNoUXBCVG4vWkxJbnd5VwpyUWp4Z09EUDlFbmVlR1BoZUJ5K2VtRldoZXc0TW8rWUJuczhDMEllWHkvZmlpMXpyZyt6TWx5QlZxcWIzM2dNCllDRUxuQXF6OW5vZ2IyK3RzTEhnN1JUVVZINGVlTDl5eDBZSHR4SWgyMy9NZkNhU0hqS2NZbDZlSlAxM2FZUkEKL3FNZ0tRSzk2OUUzQWw4MFJpS0RTRTg4aUU1T1hub1VNR3FGYVY5b1ZobGRmeWZHQnh6S2pPalBveWFwZVpZNwozT0dLc3RQdllpRWJtYmVYcHQ3ZmpWbTVvRXFFVjg3OVpreEVLTjNJSGlpcjQvZmJmUTFrOXkrdjVYL2pnamJ5CnpwUmdXcUpCbjhiSVF2SDJNMVEzdmgvQnE2RUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTHFZVXVBQ2g4VUZ2eUJaTlhBV0N6a0IxdWlrTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQlIzZ2s3b0FROEZnYWpJbFZKeUdBY2FNY1NBcWMwNFhXUnU1a3kwVmFLClY1UXhsNG9kLzZpTFR3aFEwcThxeXZSV0MvbW44SzRiYS9PVm5vT3ppUVdDeWkvc0dVS08rczU2VWFtV2p2bWkKS2ZqeXhyaWdUZGduUnJGZVFkOVdkYnB6bWxXZXkxR0RaeVcyejI4bVZYY2NpSGpxZEdWQ3ZZSDFYZ0Z3MTVFagorN0h3TWNaZW1Danc1ak5XOFpGYzZ5MGhiekZiaTQxQnRjY2VpcGc0RlJibS9uRGxEQUZjR3pKRVhBMHkvM1VZCnpzNExIRVdLNjd1SWpIQlYvTGRCZitnZ3YreVBOTVhITHhoWDdSRDFzRFdiaEpjNkNYSjc2czhXK1BBSDgzSmEKcSt2Y2VHdXplRTY1eXBVRkVEY0YrcGticWtKRGxLQ08yR1NPR0VlcVhORWU1QlBjSmF5WUhkUHRQL0szR1VTZApqUFMrK0taUllmaHRnS1dzcm5uYVlJenJDVlJRK0lkUUpvVUY5VG9KRTJPc2tlLzUyRytnZzJWMWZVcTcvRHI5CjVWSXFBWXY3RDBWWndmV0RCY24xaTZ1Q2tacStBUlR5SXdWYlpVdEFIVTF0d3djblBiMnIwbEJTYVByckhpb0UKQUNBd3ZJSnJYaU1GdU84NWZaaHZNTjA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: sidecar-injector-v2
      path: /mutate
      port: 8443
      namespace: "default"
  sideEffects: None
  admissionReviewVersions: ["v1"]
  failurePolicy: Ignore
  name: sidecar-injector-v2.default.svc
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: "Namespaced"